// svelte/src/App.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import Ticker from "./Ticker.svelte";
  import { startPolling } from "./polling";

  const btcTicker = {
    last: 0,
    bid: 0,
    ask: 0,
    volume: 0,
    priceDirection: ""
  };

  let stopPolling;
  onMount(() => {
    stopPolling = startPolling(
      "https://www.bitstamp.net/api/v2/ticker_hour/btcusd/",
      data => {
        const last = parseFloat(data.last);
        if (last > btcTicker.last) {
          btcTicker.priceDirection = "up";
        } else if (last < btcTicker.last) {
          btcTicker.priceDirection = "down";
        }
        btcTicker.last = last;
        btcTicker.bid = parseFloat(data.bid);
        btcTicker.ask = parseFloat(data.ask);
        btcTicker.volume = parseFloat(data.volume);
      },
      error => console.log(error),
      1000
    );
  });
  onDestroy(() => {
    stopPolling && stopPolling();
  });
</script>

<div id="app">
  <div class="container">
    <Ticker title="BTC/USD" {...btcTicker} />
  </div>
</div>

<style>
#app {
  text-align: center;
  background-color: #1b262d;
  color: #c4c7c9;
  font-size: calc(10px + 2vmin);
}

.container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>

// react-hooks/src/App.tsx
import React, { useReducer, useEffect } from "react";
import styles from "./App.module.css";
import { Ticker } from "./Ticker";
import { startPolling } from "./polling";
import { FetchStates } from "./FetchStates";
import { tickerReducer, tickerInitialState } from "./tickerReducer";

export const App = () => {
  const [state, dispatch] = useReducer(tickerReducer, tickerInitialState);

  useEffect(() => {
    const stopPolling = startPolling(
      "https://www.bitstamp.net/api/v2/ticker_hour/btcusd/",
      data => {
        const payload = {
          last: parseFloat(data.last),
          open: parseFloat(data.open),
          high: parseFloat(data.high),
          low: parseFloat(data.low),
          bid: parseFloat(data.bid),
          ask: parseFloat(data.ask),
          volume: parseFloat(data.volume)
        };
        dispatch({
          type: FetchStates.Success,
          payload
        });
      },
      error =>
        dispatch({
          type: FetchStates.Failure,
          error: error.message
        }),
      1000
    );

    return () => stopPolling();
  }, []);

  return (
    <div className={styles.app}>
      <div className={styles.container}>
        <Ticker title="BTC/USD" {...state} />
      </div>
    </div>
  );
};
