// svelte/src/App.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import Ticker from "./Ticker.svelte";
  import { startPolling } from "./polling";

  const btcTicker = {
    last: 0,
    bid: 0,
    ask: 0,
    volume: 0,
    priceDirection: ""
  };

  let stopPolling;
  onMount(() => {
    stopPolling = startPolling(
      "https://www.bitstamp.net/api/v2/ticker_hour/btcusd/",
      data => {
        const last = parseFloat(data.last);
        if (last > btcTicker.last) {
          btcTicker.priceDirection = "up";
        } else if (last < btcTicker.last) {
          btcTicker.priceDirection = "down";
        }
        btcTicker.last = last;
        btcTicker.bid = parseFloat(data.bid);
        btcTicker.ask = parseFloat(data.ask);
        btcTicker.volume = parseFloat(data.volume);
      },
      error => console.log(error),
      1000
    );
  });
  onDestroy(() => {
    stopPolling && stopPolling();
  });
</script>

<div id="app">
  <div class="container">
    <Ticker title="BTC/USD" {...btcTicker} />
  </div>
</div>

<style>
#app {
  text-align: center;
  background-color: #1b262d;
  color: #c4c7c9;
  font-size: calc(10px + 2vmin);
}

.container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>

// vue/src/App.vue
<template>
  <div id="app">
    <div class="container">
      <Ticker
        title="BTC/USD"
        :last="last"
        :bid="bid"
        :ask="ask"
        :volume="volume"
        :priceDirection="priceDirection"
      />
    </div>
  </div>
</template>

<script lang="ts">
import Vuex from "vuex";
import { Component, Vue } from "vue-property-decorator";
import Ticker from "./Ticker.vue";
import { startPolling } from "./polling";

Vue.use(Vuex);
const store = new Vuex.Store({
  state: {
    last: 0,
    bid: 0,
    ask: 0,
    volume: 0,
    priceDirection: ""
  },
  mutations: {
    update(state, data) {
      if (data.last > state.last) {
        state.priceDirection = "up";
      } else if (data.last < state.last) {
        state.priceDirection = "down";
      }
      state.last = parseFloat(data.last);
      state.bid = parseFloat(data.bid);
      state.ask = parseFloat(data.ask);
      state.volume = parseFloat(data.volume);
    }
  }
});

const stopPolling = startPolling(
  "https://www.bitstamp.net/api/v2/ticker_hour/btcusd",
  data => {
    store.commit("update", data);
  },
  error => console.log(error),
  3000
);

@Component({
  components: {
    Ticker
  },
  computed: {
    last: () => store.state.last,
    bid: () => store.state.bid,
    ask: () => store.state.ask,
    volume: () => store.state.volume,
    priceDirection: () => store.state.priceDirection
  },
  destroyed: () => stopPolling()
})
export default class App extends Vue {}
</script>

<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

#app {
  text-align: center;
  background-color: #1b262d;
  color: #c4c7c9;
  font-size: calc(10px + 2vmin);
}

.container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>
